# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.
log_level = "warn"
[data_collector]
enable = "true"
server_url = "https://a2demo.jonliv.es/data-collector/v0"
token = "lA27ii96Js_qINv28oBtf0_kiPM="